FROM --platform=linux/arm64 lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies in dev profile for faster iteration.
RUN cargo chef cook --recipe-path recipe.json
# Now build your actual code
COPY . .
RUN cargo build