apiVersion: 1

deleteDatasources:
  - name: OTLP Data Lake
    orgId: 1

datasources:
  - name: OTLP Data Lake
    uid: otlp-data-lake
    type: motherduck-duckdb-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: "/var/lib/grafana/datalake.duckdb"
      initSql: |
        INSTALL iceberg;
        INSTALL httpfs;
        LOAD iceberg;
        LOAD httpfs;
        SET unsafe_enable_version_guessing=true;
        SET s3_endpoint='minio:9000';
        SET s3_access_key_id='minioadmin';
        SET s3_secret_access_key='minioadmin';
        SET s3_url_style='path';
        SET s3_use_ssl=false;
        CREATE OR REPLACE VIEW traces AS
          SELECT * FROM iceberg_scan('s3://warehouse/default/traces', allow_moved_paths := true);
        CREATE OR REPLACE VIEW logs AS
          SELECT * FROM iceberg_scan('s3://warehouse/default/logs', allow_moved_paths := true);
        CREATE OR REPLACE VIEW metrics AS
          SELECT * FROM iceberg_scan('s3://warehouse/default/metrics', allow_moved_paths := true);
    editable: true
