pub mod authn_contract;
pub mod grafana_prom_smoke;
pub mod http_api;
pub mod metrics_fidelity;
pub mod metrics_layout_gold;
pub mod metrics_layout_long_grain;
#[cfg(feature = "integration-e2e")]
pub mod metrics_fidelity_postgres;
pub mod prometheus;
#[cfg(feature = "integration-e2e")]
pub mod promotion_apply_e2e;
pub mod promotion_business_row_extraction;
#[cfg(feature = "integration-e2e")]
pub mod promotion_business_table_ddl;
pub mod promotion_llm_v1;
pub mod promotion_manifest;
#[cfg(feature = "integration-e2e")]
pub mod promotion_metadata;
pub mod promotion_sqlite_local;
#[cfg(feature = "integration-e2e")]
pub mod promotion_telemetry_columns;
#[cfg(feature = "integration-e2e")]
pub mod promotion_telemetry_ingest;
#[cfg(feature = "integration-e2e")]
pub mod tenant_ducklake_registry;
#[cfg(feature = "integration-e2e")]
pub mod tenant_otlp_isolation;
#[cfg(feature = "integration-e2e")]
pub mod tenant_promotion_specs;
pub mod variant_shredding;

#[cfg(feature = "integration-e2e")]
pub mod ingest_commit_query;
#[cfg(feature = "integration-e2e")]
pub mod integration;
#[cfg(feature = "integration-e2e")]
pub mod metrics;
#[cfg(feature = "integration-e2e")]
pub mod storage_contract_validation;
