pub mod authn_contract;
pub mod http_api;
#[cfg(feature = "integration-e2e")]
pub mod promotion_business_table_ddl;
pub mod promotion_manifest;
#[cfg(feature = "integration-e2e")]
pub mod promotion_metadata;
#[cfg(feature = "integration-e2e")]
pub mod promotion_telemetry_columns;
#[cfg(feature = "integration-e2e")]
pub mod promotion_telemetry_ingest;
#[cfg(feature = "integration-e2e")]
pub mod tenant_promotion_specs;

#[cfg(feature = "integration-e2e")]
pub mod iceberg;
#[cfg(feature = "integration-e2e")]
pub mod integration;
#[cfg(feature = "integration-e2e")]
pub mod metrics;
