CREATE TABLE IF NOT EXISTS traces (
    session_id VARCHAR NOT NULL,
    trace_id VARCHAR NOT NULL,
    span_id VARCHAR NOT NULL,
    parent_span_id VARCHAR,
    app_id VARCHAR NOT NULL,
    organization_id VARCHAR,
    tenant_id VARCHAR,
    message_type VARCHAR NOT NULL,
    span_kind VARCHAR,
    timestamp TIMESTAMP_NS NOT NULL,
    end_timestamp TIMESTAMP_NS,
    attributes MAP(VARCHAR, VARCHAR),
    resource_attributes MAP(VARCHAR, VARCHAR),
    instrumentation_scope MAP(VARCHAR, VARCHAR),
    links MAP(VARCHAR, VARCHAR),
    events VARCHAR,
    status_code VARCHAR,
    status_message VARCHAR,
    http_request_method VARCHAR,
    http_request_path VARCHAR,
    http_request_headers VARCHAR,
    http_request_body VARCHAR,
    http_response_status_code INTEGER,
    http_response_headers VARCHAR,
    http_response_body VARCHAR,
    observation_type VARCHAR,
    model_name VARCHAR,
    model_provider VARCHAR,
    user_id VARCHAR,
    input_tokens BIGINT,
    output_tokens BIGINT,
    total_tokens BIGINT,
    total_cost DOUBLE,
    session_attr_id VARCHAR,
    service_name VARCHAR,
    agent_id VARCHAR,
    agent_name VARCHAR
);
