/**
 * Comprehensive inventory of all query features, functions, and aggregations.
 * Matches the checklist in docs/compat/query_features_checklist.md.
 */

import { readFileSync } from 'fs';
import { join } from 'path';

export interface QueryFeatureTestCase {
  id: string;
  category: 'selectors' | 'rate_family' | 'over_time' | 'aggregations' | 'math' | 'operators' | 'histograms' | 'modifiers' | 'discovery' | 'loki';
  name: string;
  expr: string;
  isRange: boolean;
  step?: string;
  description: string;
  validate?: (data: any) => boolean;
}

/** Shared with scripts/grafana-manual-up.sh readiness gate (single source of truth). */
export const HISTOGRAM_BUCKET_RATE_EXPR = readFileSync(
  join(__dirname, 'catalog_gates', 'histogram_bucket_rate.expr'),
  'utf8',
).trim();

export const QUERY_FEATURE_CATALOG: QueryFeatureTestCase[] = [
  // --- 1. Selectors & Matchers ---
  {
    id: 'S-01',
    category: 'selectors',
    name: 'exact_metric_name',
    expr: 'k6_http_reqs',
    isRange: true,
    description: 'Exact metric name selector without label filters',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'S-02',
    category: 'selectors',
    name: 'label_equality',
    expr: 'k6_http_reqs{job="load-generator"}',
    isRange: true,
    description: 'Label equality matcher (=)',
    validate: (data) => Array.isArray(data) && data.every(s => s.metric?.job === 'load-generator'),
  },
  {
    id: 'S-03',
    category: 'selectors',
    name: 'label_inequality',
    expr: 'http_server_request_duration_count{job!="otel-collector"}',
    isRange: true,
    description: 'Label negative matcher (!=)',
    validate: (data) => Array.isArray(data) && data.every(s => s.metric?.job !== 'otel-collector'),
  },
  {
    id: 'S-04',
    category: 'selectors',
    name: 'regex_matcher',
    expr: 'k6_http_reqs{job=~"load.*"}',
    isRange: true,
    description: 'Label regular expression matcher (=~)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'S-05',
    category: 'selectors',
    name: 'negative_regex_matcher',
    expr: 'demo_ad_served_total{category!~"telescopes"}',
    isRange: true,
    description: 'Label negative regular expression matcher (!~)',
    validate: (data) => Array.isArray(data),
  },
  {
    id: 'S-06',
    category: 'selectors',
    name: 'multi_label_matcher',
    expr: 'k6_http_reqs{job="load-generator", method=~".+"}',
    isRange: true,
    description: 'Multiple label matchers combined in a single selector',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },

  // --- 2. Rate Family Functions ---
  {
    id: 'R-01',
    category: 'rate_family',
    name: 'rate',
    expr: 'rate(k6_http_reqs[5m])',
    isRange: true,
    description: 'rate() function calculating per-second average rate of increase',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'R-02',
    category: 'rate_family',
    name: 'irate',
    expr: 'irate(k6_http_reqs[5m])',
    isRange: true,
    description: 'irate() function calculating instant per-second rate of increase',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'R-03',
    category: 'rate_family',
    name: 'increase',
    expr: 'increase(k6_http_reqs[5m])',
    isRange: true,
    description: 'increase() function calculating total increase over time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'R-04',
    category: 'rate_family',
    name: 'delta',
    expr: 'delta(k6_vus[5m])',
    isRange: true,
    description: 'delta() function calculating difference between first and last range value',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'R-05',
    category: 'rate_family',
    name: 'idelta',
    expr: 'idelta(k6_vus[5m])',
    isRange: true,
    description: 'idelta() function calculating difference between last two range points',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },

  // --- 3. Over-Time Aggregations ---
  {
    id: 'O-01',
    category: 'over_time',
    name: 'sum_over_time',
    expr: 'sum_over_time(k6_vus[5m])',
    isRange: true,
    description: 'sum_over_time() aggregating sum of samples in time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'O-02',
    category: 'over_time',
    name: 'avg_over_time',
    expr: 'avg_over_time(k6_vus[5m])',
    isRange: true,
    description: 'avg_over_time() calculating mean of samples in time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'O-03',
    category: 'over_time',
    name: 'min_over_time',
    expr: 'min_over_time(k6_vus[5m])',
    isRange: true,
    description: 'min_over_time() finding minimum sample in time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'O-04',
    category: 'over_time',
    name: 'max_over_time',
    expr: 'max_over_time(k6_vus[5m])',
    isRange: true,
    description: 'max_over_time() finding maximum sample in time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'O-05',
    category: 'over_time',
    name: 'count_over_time',
    expr: 'count_over_time(k6_vus[5m])',
    isRange: true,
    description: 'count_over_time() counting number of samples in time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'O-06',
    category: 'over_time',
    name: 'last_over_time',
    expr: 'last_over_time(k6_vus[5m])',
    isRange: true,
    description: 'last_over_time() picking most recent sample in time range',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },

  // --- 4. Vector Aggregations & Grouping ---
  {
    id: 'A-01',
    category: 'aggregations',
    name: 'sum',
    expr: 'sum(k6_http_reqs)',
    isRange: true,
    description: 'sum() aggregation combining all series',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'A-02',
    category: 'aggregations',
    name: 'avg',
    expr: 'avg(k6_vus)',
    isRange: true,
    description: 'avg() aggregation computing mean across series',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'A-03',
    category: 'aggregations',
    name: 'min',
    expr: 'min(k6_vus)',
    isRange: true,
    description: 'min() aggregation finding lowest series value',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'A-04',
    category: 'aggregations',
    name: 'max',
    expr: 'max(k6_vus)',
    isRange: true,
    description: 'max() aggregation finding highest series value',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'A-05',
    category: 'aggregations',
    name: 'count',
    expr: 'count(k6_http_reqs)',
    isRange: true,
    description: 'count() aggregation returning count of series',
    validate: (data) => Array.isArray(data) && data.length === 1 && Number(data[0].values?.[0]?.[1] ?? 0) > 0,
  },
  {
    id: 'A-06',
    category: 'aggregations',
    name: 'topk',
    expr: 'topk(3, sum by (job) (k6_http_reqs))',
    isRange: true,
    description: 'topk() aggregation returning highest k elements',
    validate: (data) => Array.isArray(data) && data.length <= 3,
  },
  {
    id: 'A-07',
    category: 'aggregations',
    name: 'bottomk',
    expr: 'bottomk(3, sum by (job) (k6_http_reqs))',
    isRange: true,
    description: 'bottomk() aggregation returning lowest k elements',
    validate: (data) => Array.isArray(data) && data.length <= 3,
  },
  {
    id: 'A-08',
    category: 'aggregations',
    name: 'by_grouping',
    expr: 'sum by (job) (k6_http_reqs)',
    isRange: true,
    description: 'by(...) clause preserving specified grouping dimensions',
    validate: (data) => Array.isArray(data) && data.every(s => 'job' in (s.metric || {})),
  },
  {
    id: 'A-09',
    category: 'aggregations',
    name: 'without_grouping',
    expr: 'avg without (method) (k6_http_reqs)',
    isRange: true,
    description: 'without(...) clause removing specified dimensions before aggregation',
    validate: (data) => Array.isArray(data) && data.every(s => !('method' in (s.metric || {}))),
  },

  // --- 5. Instant Vector Math Functions ---
  {
    id: 'M-01',
    category: 'math',
    name: 'abs',
    expr: 'abs(delta(k6_vus[5m]))',
    isRange: true,
    description: 'abs() function returning absolute values',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'M-02',
    category: 'math',
    name: 'ceil',
    expr: 'ceil(k6_vus)',
    isRange: true,
    description: 'ceil() function rounding up to nearest integer',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'M-03',
    category: 'math',
    name: 'floor',
    expr: 'floor(k6_vus)',
    isRange: true,
    description: 'floor() function rounding down to nearest integer',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'M-04',
    category: 'math',
    name: 'round_1arg',
    expr: 'round(k6_vus)',
    isRange: true,
    description: 'round() function rounding to nearest integer',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'M-05',
    category: 'math',
    name: 'round_2arg',
    expr: 'round(k6_vus, 0.5)',
    isRange: true,
    description: 'round() with to_nearest resolution argument',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },

  // --- 6. Binary Operators ---
  {
    id: 'B-01',
    category: 'operators',
    name: 'add',
    expr: 'k6_vus + 1',
    isRange: true,
    description: 'Binary addition operator (+)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-02',
    category: 'operators',
    name: 'sub',
    expr: 'k6_vus - 1',
    isRange: true,
    description: 'Binary subtraction operator (-)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-03',
    category: 'operators',
    name: 'mul',
    expr: 'k6_vus * 2',
    isRange: true,
    description: 'Binary multiplication operator (*)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-04',
    category: 'operators',
    name: 'div',
    expr: 'sum(k6_http_reqs) / sum(k6_vus)',
    isRange: true,
    description: 'Binary division operator (/)',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'B-05',
    category: 'operators',
    name: 'mod',
    expr: 'k6_vus % 3',
    isRange: true,
    description: 'Binary modulo operator (%)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-06',
    category: 'operators',
    name: 'pow',
    expr: 'k6_vus ^ 2',
    isRange: true,
    description: 'Binary power operator (^)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-07',
    category: 'operators',
    name: 'gt',
    expr: 'k6_vus > 1',
    isRange: true,
    description: 'Binary comparison greater than (>)',
    validate: (data) => Array.isArray(data),
  },
  {
    id: 'B-08',
    category: 'operators',
    name: 'lt',
    expr: 'k6_vus < 100',
    isRange: true,
    description: 'Binary comparison less than (<)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-09',
    category: 'operators',
    name: 'gte',
    expr: 'k6_vus >= 1',
    isRange: true,
    description: 'Binary comparison greater or equal (>=)',
    validate: (data) => Array.isArray(data),
  },
  {
    id: 'B-10',
    category: 'operators',
    name: 'lte',
    expr: 'k6_vus <= 100',
    isRange: true,
    description: 'Binary comparison less or equal (<=)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-11',
    category: 'operators',
    name: 'eq',
    expr: 'k6_vus == 1',
    isRange: true,
    description: 'Binary comparison equal (==)',
    validate: (data) => Array.isArray(data),
  },
  {
    id: 'B-12',
    category: 'operators',
    name: 'ne',
    expr: 'k6_vus != 0',
    isRange: true,
    description: 'Binary comparison not equal (!=)',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-13',
    category: 'operators',
    name: 'bool_modifier',
    expr: 'k6_vus > bool 1',
    isRange: true,
    description: 'Binary comparison bool modifier returning 0 or 1',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'B-14',
    category: 'operators',
    name: 'and',
    expr: 'sum(k6_http_reqs) and sum(k6_vus)',
    isRange: true,
    description: 'Logical set intersection (and)',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'B-15',
    category: 'operators',
    name: 'or',
    expr: 'sum(k6_http_reqs) or sum(k6_vus)',
    isRange: true,
    description: 'Logical set union (or)',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'B-16',
    category: 'operators',
    name: 'unless',
    expr: 'count(k6_http_reqs) unless count(k6_vus)',
    isRange: true,
    description: 'Logical set complement (unless)',
    validate: (data) => Array.isArray(data),
  },

  // --- 7. Modifiers & Classic Histograms ---
  {
    id: 'T-01',
    category: 'modifiers',
    name: 'offset',
    expr: 'k6_http_reqs offset 1m',
    isRange: true,
    description: 'Time-shift offset modifier',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'H-01',
    category: 'histograms',
    name: 'histogram_bucket',
    expr: 'sum by (le) (http_server_request_duration_bucket)',
    isRange: true,
    description: 'Classic histogram _bucket series query grouped by le',
    validate: (data) => Array.isArray(data) && data.some(s => 'le' in (s.metric || {})),
  },
  {
    id: 'H-02',
    category: 'histograms',
    name: 'histogram_count',
    expr: 'sum(http_server_request_duration_count)',
    isRange: true,
    description: 'Classic histogram _count series query',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'H-03',
    category: 'histograms',
    name: 'histogram_sum',
    expr: 'sum(http_server_request_duration_sum)',
    isRange: true,
    description: 'Classic histogram _sum series query',
    validate: (data) => Array.isArray(data) && data.length === 1,
  },
  {
    id: 'H-04',
    category: 'histograms',
    name: 'histogram_bucket_rate',
    // Prefer k6 classic histogram buckets: rate() needs ≥2 raw samples per series in
    // the window. OTLP http_server_* series go sparse under collector export backoff,
    // so rate(...[5m]) returns empty while k6 scrapes stay dense enough for CI.
    // H-01–H-03 still cover http_server_* shape without rate(); astronomy boards that
    // use rate(http_server_…_bucket[5m]) remain a separate GOLD density concern.
    expr: HISTOGRAM_BUCKET_RATE_EXPR,
    isRange: true,
    description: 'Rate of observation count by histogram bucket',
    validate: (data) =>
      Array.isArray(data) && data.length > 0 && data.some((s) => 'le' in (s.metric || {})),
  },

  // --- 8. Loki LogQL Features ---
  {
    id: 'L-01',
    category: 'loki',
    name: 'loki_stream_selector',
    expr: '{service_name=~".+"}',
    isRange: true,
    description: 'Loki stream selector matching active services',
    validate: (data) => Array.isArray(data) && data.length > 0,
  },
  {
    id: 'L-02',
    category: 'loki',
    name: 'loki_line_filter_contains',
    expr: '{service_name=~".+"} |= "HTTP"',
    isRange: true,
    description: 'Loki line filter containing substring',
    validate: (data) => Array.isArray(data) && data.length > 0 && data.every(s => (s.values || []).every((pt: [string, string]) => pt[1].includes('HTTP'))),
  },
  {
    id: 'L-03',
    category: 'loki',
    name: 'loki_line_filter_not_contains',
    expr: '{service_name=~".+"} != "DEBUG"',
    isRange: true,
    description: 'Loki line filter excluding substring',
    validate: (data) => Array.isArray(data) && data.length > 0 && data.every(s => (s.values || []).every((pt: [string, string]) => !pt[1].includes('DEBUG'))),
  },
  {
    id: 'L-04',
    category: 'loki',
    name: 'loki_line_filter_regex',
    expr: '{service_name=~".+"} |~ "GET|POST"',
    isRange: true,
    description: 'Loki line filter matching regular expression',
    validate: (data) => Array.isArray(data) && data.length > 0 && data.every(s => (s.values || []).every((pt: [string, string]) => /GET|POST/.test(pt[1]))),
  },
  {
    id: 'L-05',
    category: 'loki',
    name: 'loki_json_parser',
    expr: '{service_name=~".+"} | json',
    isRange: true,
    description: 'Loki JSON parser stage extracting attributes',
    validate: (data) => Array.isArray(data),
  },
  {
    id: 'L-06',
    category: 'loki',
    name: 'loki_parsed_field_matcher',
    expr: '{service_name=~".+"} | json | status_code = "200"',
    isRange: true,
    description: 'Loki parsed field equality filter after JSON parser',
    validate: (data) => Array.isArray(data),
  },
];
